site:
  title: Deploying MicroShift on Red Hat Device Edge
  start_page: rhde-microshift::index.adoc

content:
  sources:
  - url: ./
  - url: https://github.com/RedHatQuickCourses/rhde-build-samples.git

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui