:time_estimate: 9

= Lab: Prepare a Test Environment for Red Hat Device Edge

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Prepare a test environment for building RHEL for Edge images and managing OSTree repositories.

== Before you Begin

You need a few machines to perform the hands-on activities in this course. 

* A _development machine_ with RHEL and unrestricted `sudo`, where you will install Image Builder and RPM-OSTree tools, create test VMs using Libvirt, and also run the OpenShift client to access your MicroShift instances in other machines.

* A _test machine_ with RHEL and unrestricted `sudo`, where you will install MicroShift on package-based RHEL.

* A _package server machine_ already configured to serve DNF repositories for RHEL, Fast Datapath for RHEL, and Red Hat OpenShift Container Platform.

* A _web server machine_ with RHEL and unrestricted `sudo`, to host OSTree repositories

* A _mirror registry machine_ with RHEL and unrestricted `sudo`, to host a https://www.redhat.com/en/blog/introducing-mirror-registry-for-red-hat-openshift[mirror registry for Red Hat OpenShift].

These instructions were tested on RHEL 9.5 but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course environment, you will log in to the `workstation` VM as the user `student` with password `student`. The `workstation` VM is your _development machine_. You will start SSH sessions from the `workstation` VM to the `servera` VM, which is your _web server machine_ and also your _mirror registry machine_, using the same user.

IMPORTANT: Be sure you execute each step on the correct machine. If a step is not explicit about the machine it should be performed, it is using the same machine as its previous step.

In the course environment, the `classroom` VM, with the `materials` alias, is your _package server machine_ but you are _not_ expected to start SSH sessions nor perform any activity on it.

If you are using the same course environment where you performed the activities from the https://redhatquickcourses.github.io/rhde-build/rhde-build/1/index.html[Building Red Hat Device Edge Images] quick course, you should have some requirements already set up. They are listed here anyway, for learners that are starting this course in a new course environment.

NOTE: It should be possible to perform all activities in this course using a https://developers.redhat.com/products/rhel/download[free Red Hat Developers free subscription], which gives you access to installation media, RPM packages, and container images for RHEL and Red Hat OpenShift. If you ignore the requirements for air-gaped installation of MicroShift, you could use a single RHEL VM and adapt the steps to your own environment.

== Instructions

1. Configure your _development machine_ with the RHEL for Edge tools. It should be ready if you already performed the activities from the first course in the same course environment.
+
If something goes wrong while performing these steps and you need troubleshooting aid, please refer to the activities from the  https://redhatquickcourses.github.io/rhde-build/rhde-build/1/ch1-build/s4-install-lab.html[first course] which focus on deploying Image Builder and RPM-OSTree.

.. Install the RPM packages for the Image Builder service and its CLI. Notice that RPM-OSTree packages are also installed, as dependencies.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install osbuild-composer composer-cli*
...
Complete!
--

.. Optionally, install the RPM packages for the Cockpit service and its Composer module.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install cockpit cockpit-composer*
...
Complete!
--

.. Enable and activate the Image Builder socket.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl enable osbuild-composer.socket --now*
Created symlink /etc/systemd/system/sockets.target.wants/osbuild-composer.socket → /usr/lib/systemd/system/osbuild-composer.socket.
--

.. Optionally, enable and activate the Cockpit socket and enable remote access to Cockpit.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl enable cockpit.socket --now*
Created symlink /etc/systemd/system/sockets.target.wants/cockpit.socket → /usr/lib/systemd/system/cockpit.socket.
$ *sudo firewall-cmd --add-service=cockpit --permanent*
success
$ *sudo firewall-cmd --reload*
success
--

.. Grant your unprivileged user (the `student` user) with access to the Image Builder service.
+
[source,subs="verbatim,quotes"]
--
$ *sudo usermod -a -G weldr student*
--

.. Configure your unprivileged user with Bash command autocompletion for the Image Builder CLI.
+
[source,subs="verbatim,quotes"]
--
$ *echo 'source /etc/bash_completion.d/composer-cli' >> $HOME/.bashrc*
--

.. Log out and log in again, then verify that autocompletion works for the Image Builder CLI
+
[source,subs="verbatim,quotes,macros"]
--
$ *composer-cli kbd:[Tab]kbd:[Tab]*
blueprints  compose     distros     help        modules     projects    sources     upload
--

.. To check that you have access to the Image Builder service, list its supported image types.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli compose types*
ami
edge-commit
edge-container
edge-installer
edge-raw-image
edge-simplified-installer
gce
...
--

.. Install the JQ command-line JSON processor, because it's useful for scripting Image Builder tasks.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install jq*
...
Complete!
--

2. Configure package sources for Image Builder.
+
Your _development machine_ should be already configured with access to RHEL and MicroShift package repositories, but Image Builder does _not_ use the configurations from DNF and YUM, and, if you do not configure image sources, Image Builder will try to download packages from Red Hat repositories over the Internet.
+
If something goes wrong while performing these steps and you need troubleshooting aid, please refer to the activities from the  https://redhatquickcourses.github.io/rhde-build/rhde-build/1/ch1-build/s4-install-lab.html[first course] which focus on deploying Image Builder and RPM-OSTree.

.. Create a directory to store your repository overrides.
+
[source,subs="verbatim,quotes"]
--
$ *sudo mkdir -p /etc/osbuild-composer/repositories*
--

.. Copy the example configuration file for your distribution from the `/usr/share/osbuild-composer/` directory.
+
[source,subs="verbatim,quotes"]
--
$ *sudo cp /usr/share/osbuild-composer/repositories/rhel-9.5.json /etc/osbuild-composer/repositories/*
--

.. Modify the configuration file to match your local DNF repository. Pay attention to attributes such as `baseurl`, `rhsm`, and `check_gpg`.
+
In the course environment, you should make the following edits:
+
[source,subs="verbatim,quotes"]
--
...
include::1@samples:repos:example$rhel-9.5.json[lines=50..53]
...
include::1@samples:repos:example$rhel-9.5.json[lines=55..56]
...
include::1@samples:repos:example$rhel-9.5.json[lines=58..60]
...
include::1@samples:repos:example$rhel-9.5.json[lines=62..63]
...
--
+
You can download a https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/repositories/rhel-9.5.json[configuration file] with all changes done from the sample applications repository in GitHub.

.. Restart the Image Builder service. Be patient, it's may not be quick.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl restart osbuild-composer*
--
+
IMPORTANT: Restarting the `obuild-composer` service only works here because we assume you didn't start any compose, so there are no `osbuild-worker@<number>` services active. If there are, you must stop all of them or simply reboot the machine running Image Builder.

.. Verify that the repository overrides are in effect.
+
[source,subs="verbatim,quotes"]
--
$ *composer-cli sources list*
appstream
baseos
$ *composer-cli sources info baseos*
check_gpg = false
check_repogpg = false
...
rhsm = false
system = true
type = "yum-baseurl"
url = "http://content.example.com/rhel9.5/x86_64/dvd/BaseOS"
$ *composer-cli sources info appstream*
check_gpg = false
check_repogpg = false
...
rhsm = false
system = true
type = "yum-baseurl"
url = "http://content.example.com/rhel9.5/x86_64/dvd/ApStream"
--
+
NOTE: Later in this course, you will configure additional package sources for packages required by MicroShift. For now, it is just ensuring you have all the changes that would have been made in the https://redhatquickcourses.github.io/rhde-build[first Red Hat Device Edge course].

include::rhde-microshift:ch1-microshift:partial$s2-prepare-lab-libvirt.adoc[]

5. Configure your _web server machine_ to host OSTree repositories. It should be ready if you already performed the activities from the first course in the same course environment.
+
If something goes wrong while performing these steps and you need troubleshooting aid, please refer to the activities from the https://redhatquickcourses.github.io/rhde-build/rhde-build/1/ch2-publish/s2-ostree-lab.html[first course] which focus on configuring an Apache Web Server for OSTree repository management.

include::rhde-microshift:ch1-microshift:partial$s2-prepare-lab-apache.adoc[]

.. Install the RPM-OSTree and the lower level OSTree tooling on the web server machine, because you will need to perform maintenance on the OSTree repositories you store on it.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install rpm-ostree ostree*
...
Complete!
--

You now have your _development machine_ ready to build and test RHEL for Edge system images, and your _web server machine_ ready to store and distribute OSTree repositories for edge devices. 

== What's Next

The next lab configures the requirements for air-gapped deployments of MicroShift.

