
1. Configure your _web server machine_ with a mirror registry for Red Hat OpenShift.
+
These steps are required for all kinds of MicroShift deployment, be they on package-based or image-based, if you are performing air-gaped deployments.

.. The mirror registry for OpenShift runs as a local container, so install Podman.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install container-tools*
...
Complete!
--

.. Allow remote access to the mirror registry on the system firewall.
+
[source,subs="verbatim,quotes"]
--
$ *sudo firewall-cmd --add-port=8443/tcp --permanent*
success
$ *sudo firewall-cmd --reload*
success
--

.. Download the installer for mirror registry for Red Hat OpenShift.
+
NOTE: In a connected environment, you would get it from the https://console.redhat.com/openshift/downloads#tool-mirror-registry[downloads] page of the Red Hat Hybrid Cloud Console, but there is already a copy of the installer in the course environment at \http://content.example.com/rhde/rhocp/.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q http://content.example.com/rhde/rhocp/mirror-registry-amd64.tar.gz*
--

.. Extract the mirror registry installer in a temporary directory. You may want to keep the directory for later, if you need to uninstall the mirror registry.
+
[source,subs="verbatim,quotes"]
--
$ *mkdir mirror-registry*
$ *tar xzvf mirror-registry-amd64.tar.gz -C mirror-registry*
image-archive.tar
execution-environment.tar
mirror-registry
sqlite3.tar
--

.. Run the mirror registry installer.
+
[source,subs="verbatim,quotes"]
--
$ *sudo ./mirror-registry/mirror-registry install -v --quayHostname servera.lab.example.com  --quayRoot /var/quay --initUser microshift --initPassword redhat123*
...
INFO[2024-12-19 15:29:40] Quay installed successfully, config data is stored in /var/quay 
INFO[2024-12-19 15:29:40] Quay is available at https://servera.lab.example.com:8443 with credentials (microshift, redhat123)
--

.. If something goes wrong and you must retry the mirror registry installation, first clean the failed installation using the following command:
+
[source,subs="verbatim,quotes"]
--
$ *sudo ./mirror-registry/mirror-registry uninstall -v --quayRoot /var/quay --autoApprove*
...
INFO[2024-12-19 15:25:41] Quay uninstalled successfully 
--

.. If all is well, you should have three new containers, and three new system services.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman ps*
CONTAINER ID  IMAGE                                         COMMAND     CREATED      STATUS      PORTS                   NAMES
c4fee96c05e0  registry.access.redhat.com/ubi8/pause:8.10-5  infinity    5 hours ago  Up 5 hours  0.0.0.0:8443->8443/tcp  3e6c474403ac-infra
48a7e7a330dc  registry.redhat.io/quay/quay-rhel8:v3.12.2    registry    5 hours ago  Up 5 hours  0.0.0.0:8443->8443/tcp  quay-app
82b8559fcc97  registry.redhat.io/rhel8/redis-6:1-190        run-redis   5 hours ago  Up 5 hours  0.0.0.0:8443->8443/tcp  quay-redis
$ *systemctl status quay-app*
● quay-app.service - Quay Container
     Loaded: loaded (/etc/systemd/system/quay-app.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-12-20 09:04:13 EST; 5h 19min ago
...
$ *systemctl status quay-redis*
● quay-redis.service - Redis Podman Container for Quay
     Loaded: loaded (/etc/systemd/system/quay-redis.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-12-20 09:04:13 EST; 5h 19min ago
...
...
$ *systemctl status quay-pod*
● quay-pod.service - Infra Container for Quay
     Loaded: loaded (/etc/systemd/system/quay-pod.service; enabled; preset: disabled)
     Active: active (exited) since Mon 2025-04-28 16:35:15 EDT; 2h 9min ago
   Main PID: 33761 (code=exited, status=0/SUCCESS)
        CPU: 100ms
...
--
+
It is expected that the `quay-pod` system service runs once and exits.

.. Publish the CA certificate of the mirror registry on the Apache Web Server, so other machines can download it and connect to the mirror registry without disabling TLS validation.
+
[source,subs="verbatim,quotes"]
--
$ *sudo cp /var/quay/quay-rootCA/rootCA.pem /var/www/html/quay-rootCA.pem*
--

2. Configure your _development machine_ to access your mirror registry.
+
We will install MicroShift with common assumptions of air-gaped environments, where MicroShift should only pull container images that were previously vetted and only from private container registries, which in the course environment is the mirror registry.

.. Install the RHEL container tools because you need more than just Podman.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install container-tools*
...
Complete!
--

.. Add the CA certificate of the mirror registry to your system trusted certificates.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q http://servera.lab.example.com/quay-rootCA.pem*
$ *sudo cp quay-rootCA.pem /etc/pki/ca-trust/source/anchors*
$ *sudo update-ca-trust*
--

.. Log in to the mirror registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u microshift -p redhat123 https://servera.lab.example.com:8443*
Login Succeeded!
--

.. Copy your registry authentication credentials to a pull secret file.
+
This file replaces the pull secret of your Red Hat account, that you would use to install OpenShift and MicroShift when connected to the internet.
+
[source,subs="verbatim,quotes"]
--
$ *cp $XDG_RUNTIME_DIR/containers/auth.json mirror-pull-secret*
--
+
WARNING: You will later copy this file to your MicroShift instances, so it is important that it contains only credentials to the mirror registry, and nothing else. If you configured your mirror registry with exactly the same user name and password from the previous step, you can download a https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/microshift/mirror-pull-secret[sample pull secret file] from the course samples repository and just edit the host name of your mirror registry.

.. Download a file system copy of all required container images from the classroom server.
+
NOTE: When outside of the course environment, follow the instructions from https://docs.redhat.com/en/documentation/red_hat_build_of_microshift/4.17/html/embedding_in_a_rhel_for_edge_image/microshift-deploy-with-mirror-registry[product docs] to extract a list of MicroShift release images from the `microshift-release-info` RPM package and download them to a staging directory. In the course environment, we provide you with a backup of the staging directory to avoid the need for internet access and save on cloud bandwidth fees.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q http://content.example.com/rhde/oci/microshift-containers.tar.gz*
$ *tar xzf microshift-containers.tar.gz*
$ *ls microshift-containers/*
lvms4  openshift-release-dev
$ *wget -q http://content.example.com/rhde/oci/app-containers.tar.gz*
$ *tar xzf app-containers.tar.gz*
$ *ls app-containers*
extra-images-list.txt  flozanorht  rhel9  ubi9
--

3. Populate the mirror registry with container images required by MicroShift.

.. Download the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/sh/upload-microshift.sh[MicroShift images upload script]. It is based on the script provided by https://docs.redhat.com/en/documentation/red_hat_build_of_microshift/4.17/html/embedding_in_a_rhel_for_edge_image/index[product documentation], with minor edits.
+
Please use the copy of the script in the course samples repository as product documentation may change after this course was released.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/sh/upload-microshift.sh*
--

.. Run the MicroShift images upload script. Check carefully that its output does not indicate any errors.
+
[source,subs="verbatim,quotes"]
--
$ *sh upload-microshift.sh*
--
+
NOTE: OpenShift release images, which are reused by MicroShift, are not identified by a tag. You must refer to them by hash, so they look like different builds of the same `openshift-release-dev/ocp-v4.0-art-dev` image but they are actually completely different images.

.. You can check that the upload process worked by listing all images in the mirror registry. 
+
[source,subs="verbatim,quotes"]
--
$ *podman search servera.lab.example.com:8443/*
NAME                                                                 DESCRIPTION
servera.lab.example.com:8443/lvms4/lvms-rhel9-operator               
servera.lab.example.com:8443/openshift-release-dev/ocp-v4.0-art-dev
--
+
WARNING: The OCI distribution API is very unreliable for searching and listing container images in a container registry. It works here because there are very few images, but may not work in a production private registry with a larger number of images, including a complete set of images for Red Hat OpenShift.

4. Populate the mirror registry with container images required by sample applications for course activities.

.. Download the https://github.com/RedHatQuickCourses/rhde-build-samples/blob/main/sh/upload-apps.sh[application images upload script]. It is very similar to the MicroShift images upload script.
+
[source,subs="verbatim,quotes"]
--
$ *wget -q https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/sh/upload-apps.sh*
--

.. Run the application images upload script. Check carefully that its output does not indicate any errors.
+
[source,subs="verbatim,quotes"]
--
$ *sh upload-apps.sh*
--
+
NOTE: In production environments, it is not recommended that you mirror images based on floating tags, such as the implicit `latest` image tag, like we did here. It is recommended that you mirror using non-floating tags or image hashes.

.. You can check that the upload process worked by listing all images in the mirror registry. 
+
[source,subs="verbatim,quotes"]
--
$ *podman search servera.lab.example.com:8443/*
NAME                                                                 DESCRIPTION
servera.lab.example.com:8443/lvms4/lvms-rhel9-operator               
servera.lab.example.com:8443/openshift-release-dev/ocp-v4.0-art-dev  
servera.lab.example.com:8443/rhel9/mysql-80                          
servera.lab.example.com:8443/flozanorht/php-ubi                      
servera.lab.example.com:8443/ubi9/ubi  
--

.. Alternatively, you can open the web GUI of Red Hat Quay at `https://servera.lab.example.com:8443/` and browse the images available in your mirror registry.
+
NOTE: The mirror registry for Red Hat OpenShift only supports a subset of the features of Red Hat Quay and it is not configured for reliability and high availability.

