:time_estimate: 10

= RHEL for Edge images With MicroShift

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Deploy MicroShift on edge devices with Image Builder and RPM-OSTree.


== MicroShift Deployment with RPM-OSTree

Deploying MicroShift using edge images from image builder is not different than adding any other application on a RHEL system image. You could include MicroShift with a complete set of configuration files already embedded in an edge commit image, or you could include just MicroShift packages and add configuration files after installation as part of an on-boarding process or other day-2 activity.

But, before we drive into the specifics of including MicroShift in edge images for air-gapped environments, let's consider how image-based deployments differ than traditional package-based deployments and the most common ways that organizations use approach image-based deployments.

include::rhde-microshift:ch3-image:partial$s1-shift-left.adoc[]

== RHEL for Edge Image Workflow

In any case (shift left or not), there are benefits in building edge system images which include pre-configured MicroShift instances. You decide how much you will preconfigure, from offering an empty MicroShift instance, which is ready for remote access as a cluster administrator to offering a MicroShift, to offering a MicroShift instance with multiple workloads already deployed.

As a reminder, the following figure depicts the overall workflow for building system images and deploying them on edge devices, using RHEL for Edge.

// Copy of rhde-build ch1-build/images/s3-images-fig-1.svg
image::s1-edge-fig-3.svg[title="Workflow for building and deploying RHEL for Edge on edge devices"]

If your edge deployment is air-gapped, it is recommended that you use an edge installer image, which you can write to USB media or serve from a network boot server. If that image already embeds all your applications and configurations, it can provision devices without access to other network services, such as container image registries.

To build an edge installer image, you must first build an edge commit image, which contains an OSTree commit, and then store your edge commit image in an OSTree repository. That OSTree repository also provides system image updates for edge devices.

If you need a refresher on the finer details or troubleshooting hints for managing the RHEL for Edge image Builder service, the RPM-OSTree tooling, and OSTree repositories, please review the https://redhatquickcourses.github.io/selinux-policies/[first of the Red Hat Device Edge course].

== Image Builder and Private Container Registries

Most organizations do not allow edge devices to download content, especially software, from the Internet. They must download all content from secure internal servers. That means all software, such as RPM packages and container images, must be provided by  servers owned by your organization. This is commonly referred to as air-gapped operations.

Most organizations place similar constraints on corporate servers and development systems, and you are probably required to configure the Image Builder server to fetch all software from internal servers instead of from the Internet, that is, to build system images while operating air-gapped.

Notice that supporting air-gapped system image builds and air-gapped edge device provisioning present different constraints. The Image Builder service usually runs at a corporate site, with high speed and reliable access to package servers and container registries. Edge devices may not have good enough connectivity to those services and may consequently require that you include all artifacts in a system image.

Most Linux system administrators are used to the process of configuring RPM package servers and package repository mirrors, either using supported software such as Red Hat Satellite or by configuring their own web servers. However many system administrators are not used to configure container image registries and container image mirrors.

The Image Builder service treats RPM packages and container images in different ways:

* It does *NOT* use the system's DNF settings to access RPM repositories and requires its own configurations for accessing local package servers. That enables Image Builder to build system images for RHEL releases different than the one it's running on.

* But it *DOES* use the system's container engine settings for image policies, so you must configure the machine running the Image Builder service to access private registries and mirror registries serving container images from Red Hat and third-party vendors or for your applications developed in-house.

You configure Image Builder to access additional RPM package repositories using the Image Builder API, through either the `composer-cli` command or its Cockpit module. But you configure Image Builder to access RPM packages for RHEL packages by editing Image Builder configuration files, to create package source overrides.

You configure Image Builder to access container registries by making edits to the container engine configuration files and to the Image Builder worker configuration files:

* Edit files under `/etc/containers` to enable container image mirrors, signature verification, and TLS certificate validation.

* Edit files under `/etc/osbuild-worker/` to provide the Image Builder worker processes with credentials to access any container registry you need, including the Red Hat registries and your organization's private registries.

When you change Image Builder configuration files, like you did in the first Red Hat Device Edge course for configuring RHEL package repository overrides, you must reboot the machine running the Image Builder service. You must do the same when changing Image Builder worker configuration files because all Image Builder processes only read their configuration files at start-up.

You may find this reboot requirement unexpected. Why not just restart the Image Builder service, that is, the `osbuild-composer` service? Because Image Builder also runs a number of workers as their own Systemd units, named `osbuild-worker@<number>.service`. The number of active workers depends on the maximum number of composes running in parallel, since your last reboot. So, to restart Image Builder, you need to find out how many of such workers are active and stop all of them, one by one. So, rebooting is just easier.

== What's Next

The next and final activity of this course shows an Image Builder blueprint that configures a MicroShift instance and embeds all required configuration files and container images, and builds the edge images from local RPM repositories and a mirror registry, without requiring access to Red Hat servers over the Internet.

